version: "3.8"

services:
  web:
    image: 192.168.0.221:5000/efeso-web:dev
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret-change-me"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.0.221"

      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "john"
      POSTGRES_PASSWORD: "6d824a8fcb75e45621bded4328a9cb02"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app:
    external: true
