# Generated by Django 6.0.2 on 2026-02-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome da clínica"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Slug"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Clínica",
                "verbose_name_plural": "Clínicas",
                "indexes": [
                    models.Index(fields=["slug"], name="core_clinic_slug_d45443_idx"),
                    models.Index(
                        fields=["active"], name="core_clinic_active_a66231_idx"
                    ),
                ],
            },
        ),
    ]
