# Generated by Django 6.0.2 on 2026-02-06 02:34

import django.db.models.deletion
import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Masculino"),
                            ("female", "Feminino"),
                            ("other", "Outro"),
                            ("na", "Prefiro não informar"),
                        ],
                        max_length=20,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "whatsapp_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "extra_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone extra"
                    ),
                ),
                (
                    "how_knew_clinic",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Como conheceu a clínica",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Profissão"
                    ),
                ),
                (
                    "is_foreigner",
                    models.BooleanField(
                        default=False, verbose_name="Paciente estrangeiro"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[patients.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("rg", models.CharField(blank=True, max_length=20, verbose_name="RG")),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "categories",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Categorias"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nome (emergência)"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone (emergência)"
                    ),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Endereço"
                    ),
                ),
                (
                    "address_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "address_complement",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Complemento"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=80, verbose_name="Bairro"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome do responsável"
                    ),
                ),
                (
                    "guardian_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CPF do responsável"
                    ),
                ),
                (
                    "guardian_birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nascimento do responsável"
                    ),
                ),
                (
                    "insurance_name",
                    models.CharField(
                        blank=True,
                        default="Particular",
                        max_length=120,
                        verbose_name="Convênio",
                    ),
                ),
                (
                    "insurance_holder_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Titular do convênio"
                    ),
                ),
                (
                    "insurance_card_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número da carteirinha"
                    ),
                ),
                (
                    "insurance_guardian_cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        verbose_name="CPF do responsável (convênio)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="core.clinic",
                        verbose_name="Clínica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "full_name"],
                        name="patients_pa_clinic__f1cf8d_idx",
                    ),
                    models.Index(
                        fields=["clinic", "whatsapp_phone"],
                        name="patients_pa_clinic__90f262_idx",
                    ),
                    models.Index(
                        fields=["clinic", "cpf"], name="patients_pa_clinic__c37d1f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cpf", ""), _negated=True),
                        fields=("clinic", "cpf"),
                        name="uniq_patient_cpf_per_clinic",
                    )
                ],
            },
        ),
    ]
