# Generated by Django
import re
from django.db import migrations

def normalize_cpfs(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')

    # Iterate all patients to normalize CPF
    # Note: We must be careful about duplicates.
    # If normalizing creates a duplicate, we should skip it to avoid crashing the migration.
    # The application logic in `save()` will now handle these legacy duplicates gracefully.

    for patient in Patient.objects.all():
        if not patient.cpf:
            continue

        original_cpf = patient.cpf
        clean_cpf = re.sub(r"\D", "", original_cpf)

        if clean_cpf == original_cpf:
            continue # Already clean

        # Check if this cleaned CPF already exists in the same clinic
        # (excluding self)
        # Note: We can't rely on model methods in migrations, so we query manually
        qs = Patient.objects.filter(clinic_id=patient.clinic_id, cpf=clean_cpf).exclude(pk=patient.pk)

        if qs.exists():
            print(f"Skipping normalization for Patient ID {patient.pk} (CPF: {original_cpf}) due to collision with existing clean CPF.")
            continue

        patient.cpf = clean_cpf
        patient.save()

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_cpfs),
    ]
